version: 2
updates:
  # Maintain dependencies for dockerfiles
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      docker:
        patterns:
          - "*"
